#홈페이지에서 API서비스 신청시 받은 Appkey, Appsecret 값 설정
APP_KEY: "PSnfLpDzIItuBjGDaozyxxYlVLVBc4LElgrE"
APP_SECRET: "MODfJhtY2ZFeGYTwUEy6lM2il4dMeLpWXwzGquMDBljp2MtxINMpm/xLrWiW7V6kgquCiaJf4PxFKkUthd1apK2a8AV7x8izmubA2JB4IN3qksLLiJPPI1Y6zJGXSsvSq2NbvgV/QFWHr8jW+k6XrQQCFh/wSTLAiZ191OU7VnjnwkHJxa4="

#계좌번호 앞 8자리
CANO: "50086796"
#계좌번호 뒤 2자리
ACNT_PRDT_CD: "01"

# #실전투자
# URL_BASE: "https://openapi.koreainvestment.com:9443"
# 모의투자
URL_BASE: "https://openapivts.koreainvestment.com:29443"
# #디스코드 웹훅 URL
# DISCORD_WEBHOOK_URL: ""
